### ISSUE TITLE
Build optimize flag

### ISSUE THREAD

**Issue by fm-tibco** [project-flogo/cli#43]
Now that we are making the flogo.json imports section the single source of truth (which makes sense since we no longer have an application local vendor directory) for what is used by an application, the optimize flag must rely on parsing the non-import sections of the json to determine what is actually used.  The issue we have is that we don't have a fixed way to specify that we are using a particular contribution.   Currently we have ref and type.  Type is quite ambiguous and hard to rely on.  I propose that we go back to just using ref or introduce something less ambiguous like "pkg".  @mellistibco I know that its not your favorite, but makes it much easier to implement.  If every thing uses ref to refer to an import, we can scan the file without having to know anything about a particular resource.

So we can either go with "pkg" for package, or some sort of tag in ref like `"ref":"#rest"`, let me know what you guys think, but we should come up with resolution quickly.

**Comment by fm-tibco** [comment]
@debovema Can you also give feedback on this.  Thank you.

**Comment by fm-tibco** [comment]
Here is another possibility based on a suggestion from @skothari-tibco 

`"contrib":"github.com/…"` and `"contrib":"#rest"`, seems better than "ref" since reference is quite arbitrary.

**Comment by debovema** [comment]
I agree on the fact that only one keyword should be used and a special character to specify a package name or its alias.
Concerning this special character I would prefer @ rather than # (it makes me think of a comment).
And for the actual key word, "pkg" is good since it reminds us of the underlying object which is in fact a Go package whereas "contrib" is maybe too "OSS-oriented".

Some questions :
* if a contrib is imported inline (such as "pkg":"github.com/…") it means it is added implicitly to the same list of the imports array at runtime?
* if a package is in the imports array but is not used anywhere else in the flogo.json, it will be removed when setting the optimized flag ? If yes, we should think about an override behaviour since sometimes it's just require to import a package (when it has a init() function). That's the case of the OpenTracing listener.

**Comment by fm-tibco** [comment]
The problem with @ is that is already used in import to specify something "at" a particular version.  If you notice json schema uses "#" has a sort of pointer.   Any other ideas here?

As for pkg vs contrib, i'm on the fence.  The json is in essence to also support non-go programmers as well, so "contrib" is more apt in describing what it is in a sense.   I'll give it some thought and I'm open to other suggestions other than contrib or pkg.

If a contrib is referenced inline, it is in essence implicitly part of the "imports".

The only things that are removed on optimize are un-used contributions (action, trigger, activity and possibly function in the future).  Other imports in the imports section should be ignored by the optimize flag.

**Comment by fcastill** [comment]
I like `contrib`, I feel it makes it consistent with the use of the term "contribution" in the CLI.

**Comment by mellistibco** [comment]
I tend to think we should just stick with `ref` and support #... I mean, a ref is really what this is.

**Comment by fm-tibco** [comment]
ok so just ref and no type.  I'm ok with that as well:

```
"ref":"#log" //uses import
or
"ref":"github.com/project-flogo/contrib/log"
```
So the build tool will have to look at the imports and any import that is a contrib (activity,trigger) that doesn't have a corresponding ref will be pruned from the imports.go when using the optimize flag.
